// Country flag emojis mapping
export const countryFlags: { [key: string]: string } = {
  // North America
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  
  // Europe
  'Netherlands': '🇳🇱',
  'Germany': '🇩🇪',
  'Portugal': '🇵🇹',
  'Spain': '🇪🇸',
  'United Kingdom': '🇬🇧',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'Luxembourg': '🇱🇺',
  'Denmark': '🇩🇰',
  'Norway': '🇳🇴',
  'Sweden': '🇸🇪',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',
  'Ireland': '🇮🇪',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Slovakia': '🇸🇰',
  'Hungary': '🇭🇺',
  'Slovenia': '🇸🇮',
  'Croatia': '🇭🇷',
  'Bosnia and Herzegovina': '🇧🇦',
  'Serbia': '🇷🇸',
  'Montenegro': '🇲🇪',
  'North Macedonia': '🇲🇰',
  'Albania': '🇦🇱',
  'Greece': '🇬🇷',
  'Bulgaria': '🇧🇬',
  'Romania': '🇷🇴',
  'Moldova': '🇲🇩',
  'Ukraine': '🇺🇦',
  'Belarus': '🇧🇾',
  'Lithuania': '🇱🇹',
  'Latvia': '🇱🇻',
  'Estonia': '🇪🇪',
  'Russia': '🇷🇺',
  
  // South America
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Peru': '🇵🇪',
  'Ecuador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Paraguay': '🇵🇾',
  'Uruguay': '🇺🇾',
  'Venezuela': '🇻🇪',
  'Guyana': '🇬🇾',
  'Suriname': '🇸🇷',
  'French Guiana': '🇬🇫',
  
  // Asia
  'India': '🇮🇳',
  'China': '🇨🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'North Korea': '🇰🇵',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Myanmar': '🇲🇲',
  'Malaysia': '🇲🇾',
  'Singapore': '🇸🇬',
  'Indonesia': '🇮🇩',
  'Philippines': '🇵🇭',
  'Brunei': '🇧🇳',
  'Taiwan': '🇹🇼',
  'Hong Kong': '🇭🇰',
  'Macau': '🇲🇴',
  'Mongolia': '🇲🇳',
  'Nepal': '🇳🇵',
  'Bhutan': '🇧🇹',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Maldives': '🇲🇻',
  'Pakistan': '🇵🇰',
  'Afghanistan': '🇦🇫',
  'Iran': '🇮🇷',
  'Iraq': '🇮🇶',
  'Turkey': '🇹🇷',
  'Syria': '🇸🇾',
  'Lebanon': '🇱🇧',
  'Jordan': '🇯🇴',
  'Israel': '🇮🇱',
  'Palestine': '🇵🇸',
  'Saudi Arabia': '🇸🇦',
  'Yemen': '🇾🇪',
  'Oman': '🇴🇲',
  'United Arab Emirates': '🇦🇪',
  'Qatar': '🇶🇦',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Turkmenistan': '🇹🇲',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Georgia (Country)': '🇬🇪',
  
  // Africa
  'South Africa': '🇿🇦',
  'Nigeria': '🇳🇬',
  'Kenya': '🇰🇪',
  'Ethiopia': '🇪🇹',
  'Ghana': '🇬🇭',
  'Uganda': '🇺🇬',
  'Tanzania': '🇹🇿',
  'Rwanda': '🇷🇼',
  'Burundi': '🇧🇮',
  'Democratic Republic of the Congo': '🇨🇩',
  'Republic of the Congo': '🇨🇬',
  'Central African Republic': '🇨🇫',
  'Cameroon': '🇨🇲',
  'Chad': '🇹🇩',
  'Niger': '🇳🇪',
  'Mali': '🇲🇱',
  'Burkina Faso': '🇧🇫',
  'Senegal': '🇸🇳',
  'Gambia': '🇬🇲',
  'Guinea-Bissau': '🇬🇼',
  'Guinea': '🇬🇳',
  'Sierra Leone': '🇸🇱',
  'Liberia': '🇱🇷',
  'Ivory Coast': '🇨🇮',
  'Togo': '🇹🇬',
  'Benin': '🇧🇯',
  'Mauritania': '🇲🇷',
  'Morocco': '🇲🇦',
  'Algeria': '🇩🇿',
  'Tunisia': '🇹🇳',
  'Libya': '🇱🇾',
  'Egypt': '🇪🇬',
  'Sudan': '🇸🇩',
  'South Sudan': '🇸🇸',
  'Eritrea': '🇪🇷',
  'Djibouti': '🇩🇯',
  'Somalia': '🇸🇴',
  'Madagascar': '🇲🇬',
  'Mauritius': '🇲🇺',
  'Seychelles': '🇸🇨',
  'Comoros': '🇰🇲',
  'Malawi': '🇲🇼',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  'Botswana': '🇧🇼',
  'Namibia': '🇳🇦',
  'Lesotho': '🇱🇸',
  'Eswatini': '🇸🇿',
  'Angola': '🇦🇴',
  'Mozambique': '🇲🇿',
  
  // Oceania
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Papua New Guinea': '🇵🇬',
  'Fiji': '🇫🇯',
  'Solomon Islands': '🇸🇧',
  'Vanuatu': '🇻🇺',
  'New Caledonia': '🇳🇨',
  'French Polynesia': '🇵🇫',
  'Samoa': '🇼🇸',
  'American Samoa': '🇦🇸',
  'Tonga': '🇹🇴',
  'Kiribati': '🇰🇮',
  'Tuvalu': '🇹🇻',
  'Nauru': '🇳🇷',
  'Palau': '🇵🇼',
  'Marshall Islands': '🇲🇭',
  'Micronesia': '🇫🇲',
  
  // Caribbean
  'Jamaica': '🇯🇲',
  'Cuba': '🇨🇺',
  'Dominican Republic': '🇩🇴',
  'Haiti': '🇭🇹',
  'Puerto Rico': '🇵🇷',
  'Trinidad and Tobago': '🇹🇹',
  'Barbados': '🇧🇧',
  'Saint Lucia': '🇱🇨',
  'Grenada': '🇬🇩',
  'Saint Vincent and the Grenadines': '🇻🇨',
  'Antigua and Barbuda': '🇦🇬',
  'Dominica': '🇩🇲',
  'Saint Kitts and Nevis': '🇰🇳',
  'Bahamas': '🇧🇸',
  
  // Central America
  'Guatemala': '🇬🇹',
  'Belize': '🇧🇿',
  'El Salvador': '🇸🇻',
  'Honduras': '🇭🇳',
  'Nicaragua': '🇳🇮',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  
  // US States (using US flag for all states)
  'Alabama': '🇺🇸',
  'Alaska': '🇺🇸',
  'Arizona': '🇺🇸',
  'Arkansas': '🇺🇸',
  'California': '🇺🇸',
  'Colorado': '🇺🇸',
  'Connecticut': '🇺🇸',
  'Delaware': '🇺🇸',
  'Florida': '🇺🇸',
  'Georgia': '🇺🇸', // US State
  'Hawaii': '🇺🇸',
  'Idaho': '🇺🇸',
  'Illinois': '🇺🇸',
  'Indiana': '🇺🇸',
  'Iowa': '🇺🇸',
  'Kansas': '🇺🇸',
  'Kentucky': '🇺🇸',
  'Louisiana': '🇺🇸',
  'Maine': '🇺🇸',
  'Maryland': '🇺🇸',
  'Massachusetts': '🇺🇸',
  'Michigan': '🇺🇸',
  'Minnesota': '🇺🇸',
  'Mississippi': '🇺🇸',
  'Missouri': '🇺🇸',
  'Montana': '🇺🇸',
  'Nebraska': '🇺🇸',
  'Nevada': '🇺🇸',
  'New Hampshire': '🇺🇸',
  'New Jersey': '🇺🇸',
  'New Mexico': '🇺🇸',
  'New York': '🇺🇸',
  'North Carolina': '🇺🇸',
  'North Dakota': '🇺🇸',
  'Ohio': '🇺🇸',
  'Oklahoma': '🇺🇸',
  'Oregon': '🇺🇸',
  'Pennsylvania': '🇺🇸',
  'Rhode Island': '🇺🇸',
  'South Carolina': '🇺🇸',
  'South Dakota': '🇺🇸',
  'Tennessee': '🇺🇸',
  'Texas': '🇺🇸',
  'Utah': '🇺🇸',
  'Vermont': '🇺🇸',
  'Virginia': '🇺🇸',
  'Washington': '🇺🇸',
  'West Virginia': '🇺🇸',
  'Wisconsin': '🇺🇸',
  'Wyoming': '🇺🇸',
  'District of Columbia': '🇺🇸',
};

// Function to get flag emoji for a country/state
export const getCountryFlag = (countryName: string, isState: boolean = false): string => {
  // Handle Georgia conflict between US state and country
  if (countryName === 'Georgia') {
    return isState ? countryFlags['Georgia'] : countryFlags['Georgia (Country)'];
  }
  
  return countryFlags[countryName] || '🏳️'; // Default to white flag if not found
};
